server:
  port:8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lemonros/springcloud_0615.git
          searchPaths: config
          username: lemonros
          password: x1577475
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/